export enum College {
  COLLEGE_HUMANITIES = "COLLEGE_HUMANITIES",
  COLLEGE_SOCIAL_SCIENCES = "COLLEGE_SOCIAL_SCIENCES",
  COLLEGE_ENGINEERING = "COLLEGE_ENGINEERING",
  COLLEGE_URBAN_SCIENCE = "COLLEGE_URBAN_SCIENCE",
  COLLEGE_ARTS_SPORTS = "COLLEGE_ARTS_SPORTS",
  COLLEGE_BUSINESS = "COLLEGE_BUSINESS",
  COLLEGE_NATURAL_SCIENCES = "COLLEGE_NATURAL_SCIENCES",
  COLLEGE_LIBERAL_CONVERGENCE = "COLLEGE_LIBERAL_CONVERGENCE",
}

export const COLLEGE_LABELS: Record<College, string> = {
  [College.COLLEGE_HUMANITIES]: "인문대학",
  [College.COLLEGE_SOCIAL_SCIENCES]: "정경대학",
  [College.COLLEGE_ENGINEERING]: "공과대학",
  [College.COLLEGE_URBAN_SCIENCE]: "도시과학대학",
  [College.COLLEGE_ARTS_SPORTS]: "예술체육대학",
  [College.COLLEGE_BUSINESS]: "경영대학",
  [College.COLLEGE_NATURAL_SCIENCES]: "자연과학대학",
  [College.COLLEGE_LIBERAL_CONVERGENCE]: "자유융합대학",
};


